import { Inter } from "next/font/google";
import "./../../globals.css";
import Provider from "./../../provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function PostLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
